spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp      
  h2:
    console:
      enabled:  true  
        
  datasource:
     url:  jdbc:h2:mem:h2url
     driverClassName: org.h2.Driver  
     username:  admin
     password: admin
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect 
    

  
